/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Int;
export const TaskId = IDL.Nat32;
export const Task = IDL.Record({
  'id' : TaskId,
  'title' : IDL.Text,
  'completed' : IDL.Bool,
  'dueDate' : IDL.Opt(Timestamp),
});

export const idlService = IDL.Service({
  'addTask' : IDL.Func([IDL.Text, IDL.Opt(Timestamp)], [TaskId], []),
  'deleteTask' : IDL.Func([TaskId], [], []),
  'getActiveTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getCompletedTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getOverdueTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getTaskById' : IDL.Func([TaskId], [Task], ['query']),
  'toggleTaskCompletion' : IDL.Func([TaskId], [], []),
  'updateTask' : IDL.Func(
      [TaskId, IDL.Text, IDL.Opt(Timestamp), IDL.Bool],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Int;
  const TaskId = IDL.Nat32;
  const Task = IDL.Record({
    'id' : TaskId,
    'title' : IDL.Text,
    'completed' : IDL.Bool,
    'dueDate' : IDL.Opt(Timestamp),
  });
  
  return IDL.Service({
    'addTask' : IDL.Func([IDL.Text, IDL.Opt(Timestamp)], [TaskId], []),
    'deleteTask' : IDL.Func([TaskId], [], []),
    'getActiveTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getCompletedTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getOverdueTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getTaskById' : IDL.Func([TaskId], [Task], ['query']),
    'toggleTaskCompletion' : IDL.Func([TaskId], [], []),
    'updateTask' : IDL.Func(
        [TaskId, IDL.Text, IDL.Opt(Timestamp), IDL.Bool],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };