/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Task {
  'id' : TaskId,
  'title' : string,
  'completed' : boolean,
  'dueDate' : [] | [Timestamp],
}
export type TaskId = number;
export type Timestamp = bigint;
export interface _SERVICE {
  'addTask' : ActorMethod<[string, [] | [Timestamp]], TaskId>,
  'deleteTask' : ActorMethod<[TaskId], undefined>,
  'getActiveTasks' : ActorMethod<[], Array<Task>>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getCompletedTasks' : ActorMethod<[], Array<Task>>,
  'getOverdueTasks' : ActorMethod<[], Array<Task>>,
  'getTaskById' : ActorMethod<[TaskId], Task>,
  'toggleTaskCompletion' : ActorMethod<[TaskId], undefined>,
  'updateTask' : ActorMethod<
    [TaskId, string, [] | [Timestamp], boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];