/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Task {
    id: TaskId;
    title: string;
    completed: boolean;
    dueDate?: Timestamp;
}
export type Timestamp = bigint;
export type TaskId = number;
export interface backendInterface {
    addTask(title: string, dueDate: Timestamp | null): Promise<TaskId>;
    deleteTask(id: TaskId): Promise<void>;
    getActiveTasks(): Promise<Array<Task>>;
    getAllTasks(): Promise<Array<Task>>;
    getCompletedTasks(): Promise<Array<Task>>;
    getOverdueTasks(): Promise<Array<Task>>;
    getTaskById(id: TaskId): Promise<Task>;
    toggleTaskCompletion(id: TaskId): Promise<void>;
    updateTask(id: TaskId, title: string, dueDate: Timestamp | null, completed: boolean): Promise<void>;
}
import type { Task as _Task, TaskId as _TaskId, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addTask(arg0: string, arg1: Timestamp | null): Promise<TaskId> {
        if (this.processError) {
            try {
                const result = await this.actor.addTask(arg0, to_candid_opt_n1(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTask(arg0, to_candid_opt_n1(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async deleteTask(arg0: TaskId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTask(arg0);
            return result;
        }
    }
    async getActiveTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveTasks();
                return from_candid_vec_n2(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveTasks();
            return from_candid_vec_n2(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTasks();
                return from_candid_vec_n2(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTasks();
            return from_candid_vec_n2(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCompletedTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompletedTasks();
                return from_candid_vec_n2(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompletedTasks();
            return from_candid_vec_n2(this.uploadFile, this.downloadFile, result);
        }
    }
    async getOverdueTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOverdueTasks();
                return from_candid_vec_n2(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOverdueTasks();
            return from_candid_vec_n2(this.uploadFile, this.downloadFile, result);
        }
    }
    async getTaskById(arg0: TaskId): Promise<Task> {
        if (this.processError) {
            try {
                const result = await this.actor.getTaskById(arg0);
                return from_candid_Task_n3(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTaskById(arg0);
            return from_candid_Task_n3(this.uploadFile, this.downloadFile, result);
        }
    }
    async toggleTaskCompletion(arg0: TaskId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleTaskCompletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleTaskCompletion(arg0);
            return result;
        }
    }
    async updateTask(arg0: TaskId, arg1: string, arg2: Timestamp | null, arg3: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTask(arg0, arg1, to_candid_opt_n1(this.uploadFile, this.downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTask(arg0, arg1, to_candid_opt_n1(this.uploadFile, this.downloadFile, arg2), arg3);
            return result;
        }
    }
}
function from_candid_Task_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n4(uploadFile, downloadFile, value);
}
function from_candid_opt_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TaskId;
    title: string;
    completed: boolean;
    dueDate: [] | [_Timestamp];
}): {
    id: TaskId;
    title: string;
    completed: boolean;
    dueDate?: Timestamp;
} {
    return {
        id: value.id,
        title: value.title,
        completed: value.completed,
        dueDate: record_opt_to_undefined(from_candid_opt_n5(uploadFile, downloadFile, value.dueDate))
    };
}
function from_candid_vec_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Array<Task> {
    return value.map((x)=>from_candid_Task_n3(uploadFile, downloadFile, x));
}
function to_candid_opt_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Timestamp | null): [] | [_Timestamp] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
